language: python
python:
  - "3.4"
# install runtime and test dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -r test_requirements.txt"
  - "python ./setup.py install"
# run tests
script: nosetests
